<?php

namespace ContainerBZ8ypZK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminControllerdashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e09xbWM.App\Controller\AdminController::dashboard()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e09xbWM.App\\Controller\\AdminController::dashboard()'] = ($container->privates['.service_locator.e09xbWM'] ?? $container->load('get_ServiceLocator_E09xbWMService'))->withContext('App\\Controller\\AdminController::dashboard()', $container);
    }
}
