<?php

namespace ContainerYuPleQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F4wMV7EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F4wMV7E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F4wMV7E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.e09xbWM.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminController::new' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\AdminController::new()', 'getAdminControllernewService', true],
            'App\\Controller\\AdminController::edit' => ['privates', '.service_locator.KM74hXT.App\\Controller\\AdminController::edit()', 'getAdminControllereditService', true],
            'App\\Controller\\AdminController::delete' => ['privates', '.service_locator.upWZmvx.App\\Controller\\AdminController::delete()', 'getAdminControllerdeleteService', true],
            'App\\Controller\\AdminController::deleteComment' => ['privates', '.service_locator.P_Bnt68.App\\Controller\\AdminController::deleteComment()', 'getAdminControllerdeleteCommentService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController::list' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::list()', 'getArticleControllerlistService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.e09xbWM.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController::addComment' => ['privates', '.service_locator.upWZmvx.App\\Controller\\ArticleController::addComment()', 'getArticleControlleraddCommentService', true],
            'App\\Controller\\ArticleController::apiArticles' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::apiArticles()', 'getArticleControllerapiArticlesService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.e09xbWM.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminController:new' => ['privates', '.service_locator.mqZqLk1.App\\Controller\\AdminController::new()', 'getAdminControllernewService', true],
            'App\\Controller\\AdminController:edit' => ['privates', '.service_locator.KM74hXT.App\\Controller\\AdminController::edit()', 'getAdminControllereditService', true],
            'App\\Controller\\AdminController:delete' => ['privates', '.service_locator.upWZmvx.App\\Controller\\AdminController::delete()', 'getAdminControllerdeleteService', true],
            'App\\Controller\\AdminController:deleteComment' => ['privates', '.service_locator.P_Bnt68.App\\Controller\\AdminController::deleteComment()', 'getAdminControllerdeleteCommentService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::index()', 'getArticleControllerindexService', true],
            'App\\Controller\\ArticleController:list' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::list()', 'getArticleControllerlistService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.e09xbWM.App\\Controller\\ArticleController::show()', 'getArticleControllershowService', true],
            'App\\Controller\\ArticleController:addComment' => ['privates', '.service_locator.upWZmvx.App\\Controller\\ArticleController::addComment()', 'getArticleControlleraddCommentService', true],
            'App\\Controller\\ArticleController:apiArticles' => ['privates', '.service_locator.BCgH70e.App\\Controller\\ArticleController::apiArticles()', 'getArticleControllerapiArticlesService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\AdminController::new' => '?',
            'App\\Controller\\AdminController::edit' => '?',
            'App\\Controller\\AdminController::delete' => '?',
            'App\\Controller\\AdminController::deleteComment' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::list' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\ArticleController::addComment' => '?',
            'App\\Controller\\ArticleController::apiArticles' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\AdminController:new' => '?',
            'App\\Controller\\AdminController:edit' => '?',
            'App\\Controller\\AdminController:delete' => '?',
            'App\\Controller\\AdminController:deleteComment' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:list' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\ArticleController:addComment' => '?',
            'App\\Controller\\ArticleController:apiArticles' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
