<?php

namespace ContainerYuPleQk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControlleraddCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.upWZmvx.App\Controller\ArticleController::addComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.upWZmvx.App\\Controller\\ArticleController::addComment()'] = ($container->privates['.service_locator.upWZmvx'] ?? $container->load('get_ServiceLocator_UpWZmvxService'))->withContext('App\\Controller\\ArticleController::addComment()', $container);
    }
}
